label Gvardman - Orange PI 3 LTS
  kernel /Image
  devicetree /sun50i-h6-orangepi-3-lts.dtb
  initrd /rootfs.cpio.xz
  append console=tty0 console=ttyS0,115200n8 video=1024x600-16@60 no_console_suspend=1 consoleblank=0
